version: '3.8'

services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d myappdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    volumes:
      - postgres-data2:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - postgres
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network
  fastapi:
    build: .
    volumes:
      - ./app:/myapp/app
    environment:
      smtp_username: "${smtp_username}"
      smtp_password: "${smtp_password}"
      postgres_user: "${POSTGRES_USER}"
      postgres_password: "${POSTGRES_PASSWORD}"
      postgres_port: "${POSTGRES_PORT}"
      postgres_db: "${POSTGRES_DB}"
      postgres_server: "${POSTGRES_HOSTNAME}"
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    restart: always
volumes:
  postgres-data2:
  pgadmin-data:


networks:
  app-network: